# Generated by Django 6.0.5 on 2026-06-14 17:40

import django.core.validators
import users.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only lowercase letters, numbers and underscores allowed.",
                        regex="^[a-z0-9_]+$",
                    ),
                    users.utils.validators.validate_reserved_username,
                ],
            ),
        ),
    ]
